version: "3.7"
services:

  web:
    image: nginx
    ports:
      - "${HTTP_PORT}:80"
    # volumes:
    #   - ./web/etc/nginx/sites-enabled:/etc/nginx/sites-enabled

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file: .env

volumes:
  db_data:

networks:
  wordpress-dev:
